name: deploy-heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  CHANNEL: ${{ secrets.CHANNEL }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  APP_NAME: ${{ 'new-world-dev-tracker-bot' }}

jobs:
      
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    - name: Publish
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
        heroku run docker run -channel $CHANNEL -token $BOT_TOKEN
