name: run-container

on:
  schedule:
    - cron: '*/10* * * *'
env:
  CHANNEL: ${{ secrets.CHANNEL }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
      
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Pull Latest Image
      run: docker pull ghcr.io/pknupper/new-world-dev-tracker:main

    - name: Run Container
      run: docker run -channel $CHANNEL -token $BOT_TOKEN
